---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    expose: "true"
  name: ${project.build.finalName}
spec:
  type: NodePort
  ports:
    - port: 8091
      protocol: "TCP"
      targetPort: 8091
      name: http
    - port: 8092
      protocol: "TCP"
      targetPort: 8092
      name: p8092
    - port: 8093
      protocol: "TCP"
      targetPort: 8093
      name: p8093
    - port: 11210
      protocol: "TCP"
      targetPort: 11210
      name: p11210
